[workspace]
members = [
    "msixbundle",
    "msixbundle-cli",
]
resolver = "2"

[workspace.package]
version = "1.1.4"
edition = "2024"
license = "MIT"
repository = "https://github.com/Choochmeque/msixbundle-rs"
homepage = "https://github.com/Choochmeque/msixbundle-rs"
authors = ["You"]
